// <auto-generated />
using System;
using System.Numerics;
using ChainChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChainChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChainChatDbContext))]
    [Migration("20261010164302_AddPaymentAsset")]
    partial class AddPaymentAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChainChat.Core.Domain.AdminAccount", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.HasKey("Address")
                        .HasName("pk_admins");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.AdminAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("admin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("details");

                    b.Property<string>("Target")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_log");

                    b.ToTable("admin_audit_log", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.AdminFunding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("admin");

                    b.Property<BigInteger>("Amount")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("amount");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_admin_fundings");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_admin_fundings_address");

                    b.ToTable("admin_fundings", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.AnchorBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AnchoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anchored_at");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<long?>("ChainBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("chain_batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FromMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_message_id");

                    b.Property<int>("LeafCount")
                        .HasColumnType("integer")
                        .HasColumnName("leaf_count");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("root");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("ToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_message_id");

                    b.Property<string>("TxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_anchor_batches");

                    b.HasIndex("Root")
                        .IsUnique()
                        .HasDatabaseName("ix_anchor_batches_root");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_anchor_batches_status");

                    b.ToTable("anchor_batches", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("admin");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OnlineRecipients")
                        .HasColumnType("integer")
                        .HasColumnName("online_recipients");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.AssetTransfer", b =>
                {
                    b.Property<string>("TxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.Property<BigInteger>("Amount")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("amount");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("from");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("to");

                    b.HasKey("TxHash")
                        .HasName("pk_asset_transfers");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_asset_transfers_from");

                    b.HasIndex("To")
                        .HasDatabaseName("ix_asset_transfers_to");

                    b.ToTable("asset_transfers", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.BannedUser", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<string>("BannedBy")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("banned_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.HasKey("Address")
                        .HasName("pk_banned_users");

                    b.ToTable("banned_users", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.ChainSyncState", b =>
                {
                    b.Property<string>("ContractName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contract_name");

                    b.Property<long>("LastProcessedBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processed_block");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContractName")
                        .HasName("pk_chain_sync_states");

                    b.ToTable("chain_sync_states", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.ExchangeWallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("owner");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("private_key");

                    b.HasKey("Address")
                        .HasName("pk_exchange_wallets");

                    b.HasIndex("Owner")
                        .HasDatabaseName("ix_exchange_wallets_owner");

                    b.ToTable("exchange_wallets", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.GasDrip", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<BigInteger>("AmountWei")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("amount_wei");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.HasKey("Address")
                        .HasName("pk_gas_drips");

                    b.ToTable("gas_drips", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Group", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("created_by");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invite_code");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer")
                        .HasColumnName("max_members");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredBadgeContract")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("required_badge_contract");

                    b.PrimitiveCollection<int[]>("RequiredBadgeTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("required_badge_types");

                    b.HasKey("ConversationId")
                        .HasName("pk_groups");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_invite_code");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnchorBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("anchor_batch_id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<decimal>("ClientTimestamp")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("client_timestamp");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("conversation_id");

                    b.Property<int?>("LeafIndex")
                        .HasColumnType("integer")
                        .HasColumnName("leaf_index");

                    b.PrimitiveCollection<string[]>("MerkleProof")
                        .HasColumnType("text[]")
                        .HasColumnName("merkle_proof");

                    b.Property<string>("MessageHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("message_hash");

                    b.Property<string>("PaymentTxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("payment_tx_hash");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("prev_hash");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("sender");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("ServerReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_received_at");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("AnchorBatchId")
                        .HasDatabaseName("ix_messages_anchor_batch_id");

                    b.HasIndex("MessageHash")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_message_hash");

                    b.HasIndex("ConversationId", "Id")
                        .HasDatabaseName("ix_messages_conversation_id_id");

                    b.HasIndex("ConversationId", "Sender", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_conversation_id_sender_seq");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.MessageReaction", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("MessageId", "Address", "Emoji")
                        .HasName("pk_message_reactions");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Participant", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.HasKey("ConversationId", "Address")
                        .HasName("pk_participants");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_participants_address");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Payment", b =>
                {
                    b.Property<string>("TxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.Property<BigInteger>("Amount")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("amount");

                    b.Property<string>("Asset")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asset");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("from");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("to");

                    b.HasKey("TxHash")
                        .HasName("pk_payments");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_payments_from");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payments_status");

                    b.HasIndex("To")
                        .HasDatabaseName("ix_payments_to");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.ProcessedChainEvent", b =>
                {
                    b.Property<string>("TxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("tx_hash");

                    b.Property<int>("LogIndex")
                        .HasColumnType("integer")
                        .HasColumnName("log_index");

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("block_hash");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("TxHash", "LogIndex")
                        .HasName("pk_processed_chain_events");

                    b.HasIndex("BlockNumber")
                        .HasDatabaseName("ix_processed_chain_events_block_number");

                    b.ToTable("processed_chain_events", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.User", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptionPublicKey")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("encryption_public_key");

                    b.Property<long>("RegisteredAtBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("registered_at_block");

                    b.Property<string>("RegistrationTxHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("registration_tx_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Address")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Group", b =>
                {
                    b.HasOne("ChainChat.Core.Domain.Conversation", null)
                        .WithOne("Group")
                        .HasForeignKey("ChainChat.Core.Domain.Group", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_conversations_conversation_id");
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Message", b =>
                {
                    b.HasOne("ChainChat.Core.Domain.AnchorBatch", null)
                        .WithMany()
                        .HasForeignKey("AnchorBatchId")
                        .HasConstraintName("fk_messages_anchor_batches_anchor_batch_id");

                    b.HasOne("ChainChat.Core.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");
                });

            modelBuilder.Entity("ChainChat.Core.Domain.MessageReaction", b =>
                {
                    b.HasOne("ChainChat.Core.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_messages_message_id");
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Participant", b =>
                {
                    b.HasOne("ChainChat.Core.Domain.Conversation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_conversations_conversation_id");
                });

            modelBuilder.Entity("ChainChat.Core.Domain.Conversation", b =>
                {
                    b.Navigation("Group");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
